Release/0.5
helxplatform/appstore-chart pull request #11
Opened 2021-11-15 15:55 UTC by muralikarthikk

2021-11-16 15:44 UTC, cschreep requested changes

2021-11-16 15:44 UTC, cschreep commented on Chart.yaml
> +appVersion: 1.3.dev-c6f479bc
I think, for merges into the main branch, we should get the appstore repo a proper release, is there anything preventing us from that?

2021-12-03 21:17 UTC, pj-linebaugh commented
Maybe do a release after these latest PRs?  I have a small PR to submit too, which I will right after this.

2021-12-07 14:59 UTC, cschreep commented
> Maybe do a release after these latest PRs? I have a small PR to submit too, which I will right after this.

Sounds good to me

2022-01-27 15:37 UTC, pj-linebaugh approved these changes

2022-03-24 20:59 UTC, pj-linebaugh commented
@muralikarthikk  Images can be built from the appstore master branch now.  Can this move forward?  or maybe just restart it?

2022-06-22 14:27 UTC, closed without merging